
from .ttforge_object import TTForgeObject, TTForgeObjectInvalid
from .ttforge_object import objectNameToID

from .ttforge_object_decorator import ttforgeObjectClassFromJSON
from .ttforge_object_decorator import TTForgeObjectDecorator
from .ttforge_object_decorator import generateRegistryID
from .ttforge_object_decorator import tag, tagIcon
from .ttforge_object_decorator import TTForgeDecoratorBuilder
from .ttforge_object_decorator import TTForgeDecoratorInvalid
